POST http://localhost:4004/products
content-type: application/json

{
    "name": "Blue Marvel",
    "price": 30,
    "quantidade": 1,
    "id": "af031"
}

###

GET http://localhost:4004/products

###

GET http://localhost:4004/products/af031

###

PUT http://localhost:4004/products/af035
content-type: application/json

{
  "price": 15,
  "quantidade": 20
}

###

DELETE  http://localhost:4004/products/af031