POST http://localhost:4004/products
content-type: application/json

{
    "name": "Morbius",
    "price": 20,
    "quantidade": 1,
    "id": "smba031"
}

###

GET http://localhost:4004/products

###

GET http://localhost:4004/products/af031

###

PUT http://localhost:4004/products/smba032
content-type: application/json

{
  "price": 15,
  "quantidade": 10
}

###

DELETE  http://localhost:4004/products/af031